app.py
from flask import Flask, render_template
from common.database import Database


#Configuring Flask
app = Flask(__name__)
app.config.from_object('config')
app.secret_key = "5422"

#this method run function before all the requests
@app.before_first_request
def init_db():
    Database.initialize()

@app.route("/")
def home():
    return render_template("home.html")



# registering blueprint for users
from models.alerts.views import alert_blueprint
from models.stores.views import store_blueprint
from models.users.views import user_blueprint
app.register_blueprint(store_blueprint, url_prefix="/store")
app.register_blueprint(alert_blueprint, url_prefix="/alert")
app.register_blueprint(user_blueprint, url_prefix="/users")


























models/alerts/views.py
from flask import Blueprint, render_template, request, session, redirect, url_for
from models.alerts.alert import Alert
from models.items.item import Item
from models.users.decorator import requires_login
from common.database import Database

alert_blueprint = Blueprint('alert', __name__)




@requires_login
@alert_blueprint.route('/deactivate/<string:alert_id>')
def deactivate_alert(alert_id):
    Alert.find_by_id(alert_id).deactivate()
    return redirect(url_for('user.user_alerts'))


@requires_login
@alert_blueprint.route('/activate/<string:alert_id>')
def activate_alert(alert_id):
    Alert.find_by_id(alert_id).activate()
    return redirect(url_for('user.user_alerts'))


@requires_login
@alert_blueprint.route('/delete/<string:alert_id>')
def delete_alert(alert_id):
    Alert.find_by_id(alert_id).remove()
    return redirect(url_for('user.user_alerts'))



@alert_blueprint.route("/new", methods=['GET', 'POST'])
def create_alert():
    if request.method == "POST":
        item_name = request.form['item_name']
        item_url = request.form['item_url']
        price_limit = request.form['price_limit']
        item = Item(str(item_name), str(item_url))
        item.save_to_mongo()
        alert = Alert(session['email'],price_limit, item._id)
        alert.load_item_price()  # this is already saving to mongodb
        return redirect(url_for('user.user_alerts'))
    return render_template("alerts/create_alert.html")

@alert_blueprint.route("/edit_alerts/<string:alert_id>", methods=['GET','POST'])
def edit_alert(alert_id):
    alert = Alert.find_by_id(alert_id)
    if request.method == "POST":
        price_limit = float(request.form['price_limit'])
        alert.price_limit = price_limit
        alert.save_to_mongo()
        return redirect(url_for("user.user_alerts"))
    return render_template("alerts/edit_alert.html",alert=alert)

@alert_blueprint.route('/<string:alert_id>')
@requires_login
def get_alert_page(alert_id):
    alert = Alert.find_by_id(alert_id)
    return render_template("alerts/alert.html", alert=alert)






models/items/views.py
from flask import Blueprint


item_blueprint = Blueprint('items', __name__)

@item_blueprint.route('/item/<string:name>')
def item_page(name):
    pass


@item_blueprint.route('/load')
def load_item():
    pass

models/stores/views.py
from flask import Blueprint, render_template

store_blueprint = Blueprint('store', __name__)


@store_blueprint.route('/')
def index():
    return render_template("stores/store_list.html")

@store_blueprint.route('/store/<string:name>')
def store_page():
    pass

models/users/views.py
from flask import Blueprint, request, session, redirect, url_for, render_template
from models.users.decorator import requires_login
from models.users.user import User
from models.users import errors as UserErrors




user_blueprint = Blueprint('user',__name__)

@user_blueprint.route('/login', methods = ['GET','POST'])
def login_user():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        try:
            if User.is_login_valid(email, password):
                session['email'] = email
                return redirect(url_for(".user_alerts"))

        except UserErrors.UserErrors as e:
            return e.message
    return render_template("user/login.html")




@user_blueprint.route('/register', methods=['GET','POST'])
def register_user():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        try:
            if User.register_user(email, password):
                session['email'] = email
                return redirect(url_for(".user_alerts"))
        except UserErrors.UserErrors as e:
            return e.message
    return render_template('user/register.html')


@user_blueprint.route('/alerts')
@requires_login
def user_alerts():
    user = User.find_by_email(session["email"])
    alert = user.get_alerts()
    return  render_template("user/alerts.html", alerts=alert)


@user_blueprint.route('/logout')
def logout_user():
    session['email'] = None
    return redirect(url_for('home'))


@user_blueprint.route('check_alert/<string:user_id>')
def check_user_alerts(user_id):
    pass

templates/alerts/alert.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Alert</title>
        <!--        Google fonts Import-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900" rel="stylesheet">

        <!--        Animate.css CDN here -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">

        <!--        Linking my Own CSS for Alteration -->

        <link rel="stylesheet" type="text/css" href="https://dl.dropbox.com/s/w74wnkalxou407u/alert-s.css">



        <!--        JQuerry and javaScript libs CDN's-->

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <!--        --------------------------------------------------------->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"     crossorigin="anonymous"></script>

        <!--        Font Awasome CDN-->

        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">    


        <!--        Bootstrap CDN's Here -->

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <!--        ------------------------------------------>

        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>



    </head>






    <body>

        <!--        Navigation Bar Here -->
        <!--        Navigation Bar Here -->
        <!--        Navigation Bar Here -->
        <!--        Navigation Bar Here -->

        <header class=" nav-clr">
            <div class="container">
                <nav class="navbar navbar-expand-lg  pt-3 pb-3">
                    <a class="navbar-brand text-white" href="{{ url_for('home') }}">PriceGala</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon "><i class="fas fa-align-justify toggle-ico"></i></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav">
                            <li class="nav-item active">
                                <a class="nav-link text-white res-link" href="{{ url_for("home") }}">Home <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white res-link" href="{{ url_for("store.index") }}">Stores</a>
                            </li>
                        </ul>


                        {% if session['email'] %}
                        <ul class=" col-10 nav justify-content-end">
                            <li class="nav-item res-link">
                                <a class="nav-link text-white " href="{{ url_for('user.user_alerts') }}"><i
                                                                                                            class="fas fa-exclamation-triangle"></i> Your Alerts</a>
                            </li>
                            <li class="nav-item res-link">
                                <a class="nav-link text-white " href="{{ url_for('user.logout_user') }}"><i
                                                                                                            class="fas fa-sign-out-alt"></i> Logout</a>
                            </li>
                        </ul>



                        {% else %}
                        <ul class=" col-10 nav justify-content-end">
                            <li class="nav-item res-link">
                                <a class="nav-link text-white res-link" href="{{ url_for('user.register_user') }}"><i
                                                                                                                      class="fas fa-user-plus"></i> SignUp</a>
                            </li>
                            <li class="nav-item res-link">
                                <a class="nav-link text-white " href="{{ url_for('user.login_user') }}"><i
                                                                                                           class="fas fa-sign-out-alt"></i> Login</a>
                            </li>
                        </ul>




                        {% endif %}
                    </div>
                </nav>
            </div>
        </header>

        <!--        CENTER BODY SATART HERE -->
        <!--        CENTER BODY SATART HERE -->
        <!--        CENTER BODY SATART HERE -->
        <!--        CENTER BODY SATART HERE -->
        <!--        CENTER BODY SATART HERE -->
        <div class="container pt-5">
            <h1 class="text-white pt-1 pt-1 text-center">{{ alert.item.name }}</h1>
        </div>
        
        
        <div class="pt-3">
            <div class="container nav-clr alert-div pb-3">
                <ul class="list-group list-group-flush text-center">



                    <li class="list-group-item bg-transparent">

                        <p class="text-white text-center">
                            <small>Price Limit </small><small><strong> {{ alert.price_limit }}</strong></small><br>
                            <small>Last price found <strong>{{ alert.item.price }} </strong></small><br>
                            <small>Last Checked</small>
                            <strong>{{ alert.last_checked.strftime("%A %d %b %Y at %I-%M-%p") }}</strong>
                        </p>
                        <hr class="bg-light">
                    </li>


                </ul>
                <div class="pl-3 text-center">
                    <a href="{{ url_for("alert.edit_alert", alert_id=alert._id) }}" class="btn btn-clr"><i class="fas fa-edit"></i> Edit</a>
                    {% if alert.active %}
                    <a href="{{ url_for('alert.deactivate_alert', alert_id=alert._id) }}" class="btn dv-btn animated pulse"><i class="fas fa-times-circle"></i> Deactivate</a>
                    {% else %}
                    <a href="{{ url_for('alert.activate_alert', alert_id=alert._id) }}" class="btn dv-btn animated pulse"><i class="fas fa-check-circle"></i> Activate</a>
                    {% endif %}

                    <a href="{{ alert.item.url }}" class="btn dv-btn  animated pulse"><i class="fas fa-external-link-alt"></i> visit store</a>
                    <a href="{{ url_for("alert.delete_alert", alert_id=alert._id) }}" class="btn danger-del"><i class="fas fa-trash-alt"></i> Delete</a>
                </div>
            </div>
        </div>

        <!--        FOOTER START HERE -->
        <!--        FOOTER START HERE -->
        <!--        FOOTER START HERE -->
        <!--        FOOTER START HERE -->
        <!--        FOOTER START HERE -->

        <footer class="nav-clr fixed-bottom">

            <div class="container-fluid col-12 pb-1">
                <div class="copy-right">
                    <strong><small><p class="text-center pt-4 text-white">PriceGala copyright &copy; 2018</p></small></strong>
                </div>
                <div>
                    <small><p class="text-center footer-p2 pl-5 pr-5 pt-3 text-white">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus cursus lectus magna, eget blandit magna iaculis a. Donec efficitur nisl sit amet bibendum ullamcorper. Curabitur pellentesque ullamcorper est eget egestas.</p></small>
                </div>

            </div>


            </body>
        </html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Price Alert</title>
    <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename="css/style.css") }}">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
          integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js"
            integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em"
            crossorigin="anonymous"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.bundle.min.js"
            integrity="sha384-CS0nxkpPy+xUkNGhObAISrkg/xjb3USVCwy+0/NMzd5VxgY4CMCyTkItmy5n0voC"
            crossorigin="anonymous"></script>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <div class="container">
        <a class="navbar-brand" href="/">Price Alert</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('store.index') }}">Stores</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('alert.index') }}">Alerts</a>
                </li>
            </ul>
            <div class="container col-9">
                <ul class="nav justify-content-end">
                    {% if  session['email'] %}
                        <li class="nav-item active">
                            <a class="nav-link text-light" href="{{ url_for('user.user_alerts') }}"><i class="fas fa-exclamation-triangle"></i> Your Alerts</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link text-light" href="{{ url_for('user.logout_user') }}"><i class="fas fa-sign-out-alt"></i> Logout </a>
                        </li>

                    {% else %}

                        <li class="nav-item active">
                            <a class="nav-link text-light" href="{{ url_for('user.register_user') }}"><i class="fas fa-user-plus"></i> SignUp</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link text-light" href="{{ url_for('user.login_user') }}"><i class="fas fa-sign-in-alt"></i> Login </a>
                        </li>
                    {% endif %}

                </ul>
            </div>
        </div>

    </div>
</nav>

{% block content %}

{% endblock %}

</body>
</html>

templates/stores/create_store.html
{% extends "base.html" %}
{% block content %}
    <h3>Nothing To Show Here :(</h3>
{% endblock %}


templates/stores/edit_store.html
{% extends "base.html" %}
{% block content %}
    <h3>Nothing To Show Here :(</h3>
{% endblock %}


templates/stores/store.html
{% extends "base.html" %}
{% block content %}
    <h3>Nothing To Show Here :(</h3>
{% endblock %}


templates/user/alerts.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Alerts</title>
    <!--        Google fonts Import-->
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900" rel="stylesheet">

    <!--        Animate.css CDN here -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">

    <!--        Linking my Own CSS for Alteration -->

    <link rel="stylesheet" type="text/css" href="https://dl.dropbox.com/s/yhv5ye6o14cvvqf/alert.css">


    <!--        JQuerry and javaScript libs CDN's-->

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <!--        --------------------------------------------------------->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>

    <!--        Font Awasome CDN-->

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
          integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">


    <!--        Bootstrap CDN's Here -->

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!--        ------------------------------------------>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>


</head>


<body>

<!--        Navigation Bar Here -->
<!--        Navigation Bar Here -->
<!--        Navigation Bar Here -->
<!--        Navigation Bar Here -->

<header class=" nav-clr">
    <div class="container">
        <nav class="navbar navbar-expand-lg  pt-3 pb-3">
            <a class="navbar-brand text-white" href="{{ url_for('home') }}">PriceGala</a>
            <button class="navbar-toggler bg-light" type="button" data-toggle="collapse" data-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon "><i class="fas fa-align-justify toggle-ico"></i></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link text-white res-link" href="{{ url_for("home") }}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white res-link" href="{{ url_for("store.index") }}">Stores</a>
                    </li>
                </ul>


                {% if session['email'] %}
                    <ul class=" col-10 nav justify-content-end">
                        <li class="nav-item res-link">
                            <a class="nav-link text-white " href="{{ url_for('user.user_alerts') }}"><i
                                    class="fas fa-exclamation-triangle"></i> Your Alerts</a>
                        </li>
                        <li class="nav-item res-link">
                            <a class="nav-link text-white " href="{{ url_for('user.logout_user') }}"><i
                                    class="fas fa-sign-out-alt"></i> Logout</a>
                        </li>
                    </ul>



                {% else %}
                    <ul class=" col-10 nav justify-content-end">
                        <li class="nav-item res-link">
                            <a class="nav-link text-white res-link" href="{{ url_for('user.register_user') }}"><i
                                    class="fas fa-user-plus"></i> SignUp</a>
                        </li>
                        <li class="nav-item res-link">
                            <a class="nav-link text-white " href="{{ url_for('user.login_user') }}"><i
                                    class="fas fa-sign-out-alt"></i> Login</a>
                        </li>
                    </ul>




                {% endif %}
            </div>
        </nav>
    </div>
</header>

<!--        CENTER BODY SATART HERE -->
<!--        CENTER BODY SATART HERE -->
<!--        CENTER BODY SATART HERE -->
<!--        CENTER BODY SATART HERE -->
<!--        CENTER BODY SATART HERE -->
<div class="container">
    <h1 class="text-white pl-4 pt-1 pt-1">Alerts</h1>
</div>

<div class="container nav-clr alert-div pb-3">

    <ul class="list-group list-group-flush ">


        {% for alert in alerts %}
            <li class="list-group-item bg-transparent">
            <a class=" link-clr"
               href="{{ url_for("alert.get_alert_page", alert_id=alert._id) }}">{{ alert.item.name }}</a>
            <p class="text-white">
                {% if alert.active %}
                <i class="pb-5 fas fa-check-circle fa-3x float-right pb-5"></i>
                {% else %}
                <i class="fas fa-times-circle fa-3x float-right pb-5"></i>
                {% endif %}
                <small>Last price found <strong>{{ alert.item.price }} </strong></small>
                <br>
                <small>Price Limit</small>
                <small><strong> {{ alert.price_limit }}</strong></small>
                <br>
                <small>Last Checked</small>
                <strong>{{ alert.last_checked.strftime("%A %d %b %Y at %I-%M-%p") }}</strong>
            </p>
            <hr class="bg-light">
        {% endfor %}
        </li>


    </ul>
    <div class="pl-3">
        <a href="{{ url_for("alert.create_alert") }}" class="btn btn-clr"><i class="fas fa-plus"></i> Create new</a>
    </div>
</div>


<!--        FOOTER START HERE -->
<!--        FOOTER START HERE -->
<!--        FOOTER START HERE -->
<!--        FOOTER START HERE -->
<!--        FOOTER START HERE -->

<footer class="nav-clr ">

    <div class="container-fluid col-12 pb-1">
        <div class="copy-right">
            <strong>
                <small><p class="text-center pt-4 text-white">PriceGala copyright &copy; 2018</p></small>
            </strong>
        </div>
        <div>
            <small><p class="text-center footer-p2 pl-5 pr-5 pt-3 text-white">Lorem ipsum dolor sit amet, consectetur
                adipiscing elit. Vivamus cursus lectus magna, eget blandit magna iaculis a. Donec efficitur nisl sit
                amet bibendum ullamcorper. Curabitur pellentesque ullamcorper est eget egestas.</p></small>
        </div>

    </div>


</body>
</html>

templates/user/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <!--        Google fonts Import-->
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900" rel="stylesheet">

    <!--        Animate.css CDN here -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">

    <!--        Linking my Own CSS for Alteration -->

    <link rel="stylesheet" type="text/css" href="https://dl.dropbox.com/s/a3vzkoykjecekvn/style.css">


    <!--        JQuerry and javaScript libs CDN's-->

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <!--        --------------------------------------------------------->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>

    <!--        Font Awasome CDN-->

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
          integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">


    <!--        Bootstrap CDN's Here -->

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!--        ------------------------------------------>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>


</head>

<!--     body start here -->
<body>
<div class="container pt-3">
    <a class="link-clr" href="{{ url_for("home") }}"><i class="fas fa-chevron-left mr-2"></i> Back to Home</a>
</div>
<div class="container col-xl-4 main-div animated bounceInDown mb-5">
    <div class="mx-auto form-clr form-div">
        <div class="text-center  mx-auto ico-d">
            <img src="https://dl.dropbox.com/s/vs8tpvc3h7yvywl/lock_icon.png" class="icon-h">
            <!--                            <i class="fas fa-unlock-alt fa-5x icon-clr icon-size"></i>-->
        </div>


        <div class="col-10 mx-auto pt-4">
            <form action="{{ url_for('user.login_user') }}" method="post">

                <div class="form-group pt-3 e-icon">
                    <label for="exampleInputEmail1"> Email address</label>
                    <i class="fas fa-user user-ico"></i>
                    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
                           placeholder="Enter email" name="email">

                </div>
                <div class="form-group pt-3">
                    <label for="exampleInputPassword1">Password</label>
                    <i class="fas fa-lock lock_ico"></i>
                    <input type="password" class="form-control " id="exampleInputPassword1" placeholder="Password"
                           name="password">
                </div>

                <div class="mx-auto text-center pb-4 pt-4">
                    <button type="submit" class="btn  btn-clr"><i class="fas fa-sign-in-alt"></i> Login</button>
                </div>
                <div class="col-12 mx-auto text-center">
                    <a class="link-clr" href="{{ url_for('user.register_user') }}">Not a member? Signup</a>
                </div>

            </form>

        </div>
    </div>
</div>


<footer class="footer">
    <div class="container-fluid col-12 pb-1">
        <div class="copy-right">
            <strong>
                <small><p class="text-center pt-4">PriceGala copyright &copy; 2018</p></small>
            </strong>
        </div>
        <div>
            <small><p class="text-center footer-p2 pl-5 pr-5 pt-3">Lorem ipsum dolor sit amet, consectetur adipiscing
                elit. Vivamus cursus lectus magna, eget blandit magna iaculis a. Donec efficitur nisl sit amet bibendum
                ullamcorper. Curabitur pellentesque ullamcorper est eget egestas.</p></small>
        </div>
    </div>

</footer>


</body>

</html>